FROM node:lts-slim

WORKDIR /app

COPY tsconfig*.json ./
COPY package.json ./
COPY .env ./
COPY src/ src/
COPY assets/ assets/
COPY yarn.lock ./

RUN yarn
RUN yarn add sharp --ignore-engines
RUN yarn build

EXPOSE 3000

CMD ["yarn", "start"]
